name: Workflow with options

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      deploy-dev:
        description: Deploy Dev
        type: boolean
        required: true
        default: true

      deploy-test:
        description: Deploy Test
        type: boolean
        required: true
        default: true

      deploy-preprod:
        description: Deploy Pre-production
        type: boolean
        required: true
        default: true

      deploy-prod:
        description: Deploy Production
        type: boolean
        required: true
        default: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Where am i?
        run: echo "environment is ${{ github.env }}"

  deploy-dev:
    if: ${{ always() && needs.*.result == 'success' && inputs.deploy-dev }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    steps:
      - name: Where am i?
        run: echo "environment is ${{ github.env }}"
  
  deploy-test:
    if: ${{ always() && (needs.*.result == 'success' || needs.*.result == 'skipped') && inputs.deploy-test }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    environment:
      name: 'Test'
    steps:
      - name: Where am i?
        run: echo "environment is ${{ github.env }}"
        
  deploy-preprod:
    if: ${{ always() && (needs.*.result == 'success' || needs.*.result == 'skipped') && inputs.deploy-preprod }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [deploy-test]
    environment:
      name: 'Preprod'
    steps:
      - name: Where am i?
        run: echo "environment is ${{ github.env }}"
        
  deploy-prod:
    if: ${{ always() && (needs.*.result == 'success' || needs.*.result == 'skipped') && inputs.deploy-prod }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [ deploy-preprod]
    environment:
      name: 'Prod'
    steps:
      - name: Where am i?
        run: echo "environment is ${{ github.env }}"
