name: Workflow with options

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      #environment:
      #  type: environment
      #  description: Deploy environment
      #  required: true
      environment:
        type: multi-choice
        description: Deploy environment
        required: true
        options:
        - dev
        - test
        - preprod
        - prod
        
        
      skip-needs-checks:
        description: Force deployment to selected invironments without checking pre-requisite needs
        type: boolean
        required: true
        default: false      
      deploy-dev:
        description: Deploy Dev
        type: boolean
        required: true
        default: true
      deploy-test:
        description: Deploy Test
        type: boolean
        required: true
        default: true
      deploy-preprod:
        description: Deploy Pre-production
        type: boolean
        required: true
        default: true
      deploy-prod:
        description: Deploy Production
        type: boolean
        required: true
        default: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Where am i?
        run: echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"

  deploy-dev:
    #if: ${{ github.event.inputs.environment }} 
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    steps:
      - name: Where am i?
        run: echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
  
  deploy-test:
    #if: ${{ inputs.deploy-test || inputs.skip-needs-checks }} 
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    environment:
      name: 'Test'
    steps:
      - name: Where am i?
        run: echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
        
  deploy-preprod:
    #if: ${{ inputs.deploy-preprod || inputs.skip-needs-checks }} 
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [deploy-dev, deploy-test]
    environment:
      name: 'Preprod'
    steps:
      - name: Where am i?
        run: echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
        
  deploy-prod:
    #if: ${{ inputs.deploy-prod || inputs.skip-needs-checks }} 
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [deploy-dev, deploy-preprod]
    environment:
      name: 'Prod'
    steps:
      - name: Where am i?
        run: echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
