name: Deploy Build to Selected Environment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      deploy-dev:
        description: Deploy Dev
        type: boolean
        required: true
        default: true

      deploy-test:
        description: Deploy Test
        type: boolean
        required: true
        default: true

      deploy-preprod:
        description: Deploy Pre-production
        type: boolean
        required: true
        default: true

      deploy-prod:
        description: Deploy Production
        type: boolean
        required: true
        default: true

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Build
        run: echo "Building stuff... please wait"

  pre-deploy-check:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List environments to deploy
        run: |
          echo Dev: ${{inputs.deploy-dev}}
          echo Test: ${{inputs.deploy-test}}
          echo PreProd: ${{inputs.deploy-preprod}}
          echo Prod: ${{inputs.deploy-prod}}

          if [[ ${{inputs.deploy-dev}} == "false" && ${{inputs.deploy-test}} == "false" && ${{inputs.deploy-preprod}} == "false" && ${{inputs.deploy-prod}} == "false" ]]; then
              echo Nah dude! Please select at least 1 environment to deploy!
              exit 1;
          fi

  deploy-dev:
    if: ${{ always() && needs.*.result == 'success' && inputs.deploy-dev }}
    uses: ./.github/workflows/deploy-environment.yml
    needs: pre-deploy-check
    with:
      environment: Dev
    secrets: inherit
    permissions:
      contents: none
  
  deploy-test:
    if: ${{ always() && (needs.*.result == 'success' || needs.*.result == 'skipped') && inputs.deploy-test }}
    uses: ./.github/workflows/deploy-environment.yml
    needs: deploy-dev
    with:
      environment: Test
    secrets: inherit
    permissions:
      contents: none
        
  deploy-preprod:
    if: ${{ always() && (needs.*.result == 'success' || needs.*.result == 'skipped') && inputs.deploy-preprod }}
    uses: ./.github/workflows/deploy-environment.yml
    needs: deploy-test
    with:
      environment: Preprod
    secrets: inherit
    permissions:
      contents: none
        
  deploy-prod:
    if: ${{ always() && (needs.*.result == 'success' || needs.*.result == 'skipped') && inputs.deploy-prod }}
    uses: ./.github/workflows/deploy-environment.yml
    needs: deploy-preprod
    with:
      environment: Prod
    secrets: inherit
    permissions:
      contents: none
